config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end

  get 'dashboard' => 'home#dashboard'

  authenticated :user do
    root to: 'posts#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments

  def self.leader_board
    users = self.includes({posts: :comments}, :comments)
    data = []
    users.each do |usr|
      usr_data = {}
      usr_data[:email] = usr.email
      usr_data[:posts_count] = usr.posts.size

      usr_data[:incoming_comments_count] = usr.posts.collect do |post|
        post.comments.select do |comment|
          comment.user_id == usr.id
        end.size
      end.reduce(:+)

      usr_data[:outgoing_comments_count] = usr.comments.count do |comment|
        !usr.posts.collect(&:id).include?(comment.post_id)
      end

      score = 0
      score += 10*usr_data[:posts_count]
      score += 3*usr_data[:outgoing_comments_count]
      score += usr_data[:incoming_comments_count]
      usr_data[:score] = score

      data.push(usr_data)
    end

    data.sort_by!{|item| item[:score]}.reverse!

    return data
  end

  # def post_ids
  #   @post_ids ||= self.posts.pluck(:id)
  # end
  #
  # def posts_count
  #  self.post_ids.size
  # end
  #
  # def outgoing_comments_count
  #   @outgoing_comments_count ||= self.comments
  #                                    .where.not(post_id: self.post_ids)
  #                                    .count
  # end
  #
  # def incoming_comments_count
  #   @incoming_comments_count ||= Comment.where.not(user_id: self.id)
  #                                       .where(post_id: self.post_ids)
  #                                       .count
  # end
  #
  # def score
  #   return @score if @score
  #   @score = 0
  #   @score += 10*self.posts_count
  #   @score += 3*self.outgoing_comments_count
  #   @score += self.incoming_comments_count
  #   return @score
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    flash[:alert] = "Please check your comment" unless @comment.save
    redirect_to post_path(@post)
  end

private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
    @leader_board = User.leader_board
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:mine]
      @posts = current_user.posts
    else
      @posts = Post.all
    end
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
    @comments = @post.comments.reverse
    @new_comment = @post.comments.new
  end

private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_tag(msg, msg_type)
    return unless msg.present?
    if msg_type == "notice"
      msg_type = "info"
    elsif msg_type == "alert"
      msg_type = "danger"
    end

    content_tag(:div, class: "alert alert-#{msg_type} alert-dismissible", role: "alert") do
      button_tag(class: "close", "data-dismiss" => "alert") do
        content_tag(:span, raw("&times;"), "aria-hidden" => true) +
          content_tag(:span, "Close", class: "sr-only")
      end + msg
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment well">
  <p>
    <%= comment.body %>
  </p>
  <p class="text-right">
    <%= comment.user.email %> | <%= comment.created_at.strftime("%e %b, %Y") %>
  </p>
</div>

app/views/common/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Blogger", root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "Add a Post", new_post_path %>
            </li>
            <li>
              <%= link_to "All Posts", posts_path %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to "My Posts", posts_path(mine: true) %>
                </li>
                <li>
                  <%= link_to "Dashboard", dashboard_path %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/home/dashboard.html.erb
<div id="dashboard">
  <h1>Leaderboard</h1>
  <table class="table">
    <thead>
      <tr>
        <th>
          User
        </th>
        <th>
          Posts Authored
        </th>
        <th>
          Comments Made
        </th>
        <th>
          Comments Received
        </th>
        <th>
          Points
        </th>
      </tr>
    </thead>
    <tbody>
      <% @leader_board.each do |usr| %>
          <tr class="<%= (usr[:email] == current_user.email) ? 'info' : '' %>">
            <td>
              <%= usr[:email] %>
            </td>
            <td>
              <%= usr[:posts_count] %>
            </td>
            <td>
              <%= usr[:outgoing_comments_count] %>
            </td>
            <td>
              <%= usr[:incoming_comments_count] %>
            </td>
            <td>
              <%= usr[:score] %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'common/header' %>

<div class="container">
  <div class="flash_messages">
    <%= flash_tag(notice, "notice") %>
    <%= flash_tag(alert, "alert") %>
  </div>
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_post.html.erb
<div class="post well">
  <h3><%= link_to post.title, post_path(post) %></h3>
  <p>
    <%= post.body %>
  </p>
  <p class="text-right">
    <%= post.user.email %> | <%= post.created_at.strftime("%e %b, %Y") %> | <%= pluralize post.comments.size, "comment" %>
  </p>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>
<%= render @posts %>

app/views/posts/new.html.erb
<h1>Add a New Post</h1>

<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.submit "Add Post", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>
  <%= @post.body %>
</p>

<h3>Comments</h3>
<%= simple_form_for [@post, @new_comment], html: {class: "well"} do |f| %>
  <%= f.input :body, label: false %>
  <%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>

<%= render @comments %>